[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, x-my-secret"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
